#!/usr/bin/Rscript

# This script prepares a data file to use for displaying gene regions
# as a heatmap on top of the ideograms

# Loading the required package
library(GenomicRanges)

# Reading the genes as a GRanges object as they were already generated by another analysis
# DEPENDENCY: gene_analysis/genes.RData
load("../../gene_analysis/genes.RData")

# Reading in the bins over which to tally the number of genes
# DEPENDENCY : figures/figure_3_circos/gmax4_3Mb_bins.RData
load("gmax4_3Mb_bins.RData")

# Let us write a function that takes a GRanges object as input, some bins to count over
# and the name of a file to which the Circos data track will be output
output_track <- function(x, bins, output_file) {
	bins$count <- countOverlaps(bins, x)
	bins <- as.data.frame(bins)
	bins <- bins[, c("seqnames", "start", "end", "count")]
	write.table(bins, file = output_file, col.names = FALSE, row.names = FALSE,
		    quote = FALSE, sep = "\t")
}

# OUTPUT: figures/figure_3_circos/genes_heatmap.txt
output_track(genes, gmax4_3Mb_bins, "genes_heatmap.txt")

