#!/usr/bin/Rscript

# Loading the GenomicRanges package
library(GenomicRanges)

# Loading the function
# DEPENDENCY : scripts/filter_sniffles.R
source("../scripts/filter_sniffles.R")

# Looping over all 17 samples
# DEPENDENCY : utilities/line_ids.txt
for(i in read.table("../utilities/line_ids.txt", header = TRUE, stringsAsFactors = FALSE)[[1]]) {
	# This dependency is generated by the script that calls it
	input_file <- paste0(i, "_sniffles_minreads3_hom70.vcf")

	filter_sniffles(vcf.file = input_file,
			keep_hets = FALSE,
			max_N_del = 0,
			keep_homref = FALSE,
			chrom_pattern = "^Gm[0-9]{2}$",
			remove_N_ins = TRUE,
			N_ins_range = 20,
			# DEPENDENCY : refgenome/Gmax_508_v4.0_mit_chlp.fasta
			refseq = "../refgenome/Gmax_508_v4.0_mit_chlp.fasta",
			min_sv_size = 50,
			max_sv_size = 500000,
# OUTPUT : nanopore_sv_calling/AC2001_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/ALTA_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/MAPLE_ISLE_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/MAPLE_PRESTO_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_09_35C_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_CARMAN_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_DRAYTON_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_EMBRO_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_LAKEVIEW_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_MADOC_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_OXFORD_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_PETREL_2_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_PRUDENCE_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OAC_STRATFORD_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/OT09-03_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/QS5091.50J_hom70_filtered.vcf
# OUTPUT : nanopore_sv_calling/ROLAND_hom70_filtered.vcf
			output_file = paste0(i, "_hom70_filtered.vcf"),
			keep.ins.seq = TRUE, 
			keep.ref.seq = TRUE, 
			sample.name = "",
			qual.field = "QUAL",
			other.field = '',
			check.inv = FALSE,
			keep.ids = FALSE,
			nocalls = TRUE,
			out.fmt = "gr",
			min.sv.size = 30)
}

