#!/usr/bin/Rscript

# File initially created on Friday, October 5, 2020

# Getting the path to the bcftools executable from the command line
bcftools <- commandArgs(trailingOnly = TRUE)[1]

# Creating a list to store each of the data.frames
data_list <- list()

# Looping over all samples to generate their metainfo file
for(i in c("MAPLE_PRESTO", "OAC_CARMAN", "QS5091.50J", "OAC_EMBRO")) {
	command <- paste0(bcftools, " query --format ",
			  "'%INFO/IMPRECISE\t%INFO/PRECISE\t%INFO/SVLEN\t%INFO/SVTYPE\t",
			  "%INFO/MAX_SVLEN\t%INFO/NO_ALIGNMENT\t%INFO/GATHER_DATA_FAILED\t",
			  "%INFO/BELOW_THRESHOLDS\t%INFO/REALIGNED\t%INFO/CONTIG_LEN\t",
			  "%INFO/IDENTITY\t%INFO/GAPS\t%INFO/OVERLAP\t%INFO/DISTANCE_RATIO\t",
			  "%INFO/OFFSET\t%INFO/ORIGINAL_LEN\n' ")

	# DEPENDENCY : refined SV VCF files to which metadata has been added (at the SV_NORMALIZATION STEP)
	system(paste0(command, i, "_realigned_metainfo.vcf > ", i, "_metainfo.txt"))

	# Then we read each of the data.frames as the element of a list
	i_data <- read.table(paste0(i, "_metainfo.txt"), 
			     header = FALSE, sep = "\t", na.strings = ".",
			     col.names = c("imprecise", "precise", "svlen", "svtype", "max_svlen",
					   "no_alignment", "gather_data_failed", "below_thresholds",
					   "realigned", "contig_len", "identity", "gaps", "overlap",
					   "distance_ratio", "offset", "original_len"),
			     stringsAsFactors = FALSE)

	# Adding the name of the sample as a column
	i_data$sample <- i

	# Adding the data.frame to the list
	data_list[[i]] <- i_data
}

# Joining all the data.frames into a single one
all_metainfo <- do.call("rbind", data_list)

# Creating a new column for the flag generated by the program
all_metainfo$flag <- NA
# And filling it with the appropriate value
all_metainfo$flag[!is.na(all_metainfo$max_svlen)] <- "MAX_SVLEN"
all_metainfo$flag[!is.na(all_metainfo$no_alignment)] <- "NO_ALIGNMENT"
all_metainfo$flag[!is.na(all_metainfo$gather_data_failed)] <- "GATHER_DATA_FAILED"
all_metainfo$flag[!is.na(all_metainfo$below_thresholds)] <- "BELOW_TRESHOLDS"
all_metainfo$flag[!is.na(all_metainfo$realigned)] <- "REALIGNED"
# Sanity check
any(is.na(all_metainfo$flag))
# Checking if the only NA are duplications and inversions
tapply(all_metainfo$flag, all_metainfo$svtype, function(x) sum(is.na(x)))

# Also changing the imprecise column into a logical one
all_metainfo$imprecise <- as.logical(all_metainfo$imprecise)
all_metainfo$imprecise[!(is.na(all_metainfo$precise))] <- FALSE
any(is.na(all_metainfo$imprecise))
table(all_metainfo$imprecise)

# Saving to a .RData file
save(all_metainfo, file = "all_metainfo.RData")

