#!/prg/R/4.0/bin/Rscript

# Figure s23 shows the phylogenetic trees obtained from SNPs and SVs

# Loading the ape package
library(ape)

# Loading the main tree data
# DEPENDENCY : structure_analysis/trees/snp_outtree
snp_tree <- read.tree("../structure_analysis/trees/snp_outtree")
# DEPENDENCY : structure_analysis/trees/sv_outtree
sv_tree <- read.tree("../structure_analysis/trees/sv_outtree")

# Loading the bootstrapped trees data
# DEPENDENCY : structure_analysis/trees/SNP_BOOTSTRAP (bootstrapped trees made from SNVs)
snp_files <- dir("../structure_analysis/trees/bootstrap", pattern = "outtree", recursive = TRUE)
snp_files <- grep("snp_bootstrap", snp_files, value = TRUE)
snp_bootstrap <- list()

for(i in snp_files) {
	id <- gsub("/", "_", i)
	snp_bootstrap[[id]] <- read.tree(paste0("../structure_analysis/trees/bootstrap/", i))
}

# DEPENDENCY : structure_analysis/trees/SV_BOOTSTRAP (bootstrapped trees made from SVs)
sv_files <- dir("../structure_analysis/trees/bootstrap", pattern = "outtree", recursive = TRUE)
sv_files <- grep("sv_bootstrap", sv_files, value = TRUE)
sv_bootstrap <- list()

for(i in sv_files) {
	id <- gsub("/", "_", i)
	sv_bootstrap[[id]] <- read.tree(paste0("../structure_analysis/trees/bootstrap/", i))
}

# Reading in the Structure data for SNPs
# DEPENDENCY : structure_analysis/structure.5.meanQ
snp_structure <- read.table("../structure_analysis/structure.5.meanQ")
snp_structure <- as.matrix(snp_structure)

# A function to imitate the color selection in ggplot2
# Taken from Stack Overflow: https://stackoverflow.com/questions/8197559/emulate-ggplot2-default-color-palette
gg_color_hue <- function(n) {
	hues = seq(15, 375, length = n + 1)
	hcl(h = hues, l = 65, c = 100)[1:n]
}

gg_colors <- gg_color_hue(5)
pop_colors <- gg_colors[apply(snp_structure, 1, which.max)]

# DEPENDENCY : structure_analysis/trees/sv_distance.mdist.id (this file is generated by the same script as the tree)
samples <- read.table("../structure_analysis/trees/sv_distance.mdist.id")[[2]]
names(pop_colors) <- samples

# Getting the support for the nodes in both main trees by looking at the bootstrapped trees
snp_support <- prop.clades(snp_tree, snp_bootstrap)
stopifnot(all(!is.na(snp_support)))
sv_support <- prop.clades(sv_tree, sv_bootstrap)
stopifnot(all(!is.na(sv_support)))

# Computing some statistics
## Number of nodes in the SNP tree that are found in the SV tree
sum(!is.na(prop.clades(snp_tree, sv_tree)))
## Number of nodes in the SNP tree found in at least one bootstrapped SV tree
sum(!is.na(prop.clades(snp_tree, sv_bootstrap)))

# Also computing a mantel.test from the distance matrices
mantel.test(as.matrix(read.table("../structure_analysis/trees/sv_distance.mdist")),
	    as.matrix(read.table("../structure_analysis/trees/snp_distance.mdist")))

# Saving the figure as Figure sA
png("figure_s23.png", width = 9.5, height = 6, units = "in", res = 500)

opar <- par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))

plot(rotate(rotate(sv_tree, 124), 160), type = "fan", tip.color = pop_colors[sv_tree$tip.label], font = 1, cex = 0.45)
nodelabels(sv_support, cex = 0.4, bg = "white")
text(x = -0.28, y = 0.28, labels = "A", cex = 2.5)

plot(snp_tree, tip.color = pop_colors[snp_tree$tip.label], type = "fan", font = 1, cex = 0.45)
nodelabels(snp_support, cex = 0.4, bg = "white")
text(x = -0.28, y = 0.32, labels = "B", cex = 2.5)

par(opar)

dev.off()

